# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'board.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Board(object):
    def setupUi(self, Board):
        Board.setObjectName("Board")
        Board.resize(287, 900)
        Board.setMinimumSize(QtCore.QSize(0, 0))
        Board.setMaximumSize(QtCore.QSize(287, 900))
        self.verticalLayout = QtWidgets.QVBoxLayout(Board)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lab_task_count = QtWidgets.QLabel(Board)
        self.lab_task_count.setObjectName("lab_task_count")
        self.horizontalLayout_2.addWidget(self.lab_task_count)
        self.lab_title = QtWidgets.QLabel(Board)
        self.lab_title.setMaximumSize(QtCore.QSize(16777215, 30))
        self.lab_title.setObjectName("lab_title")
        self.horizontalLayout_2.addWidget(self.lab_title)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.btn_open_add = QtWidgets.QPushButton(Board)
        self.btn_open_add.setMaximumSize(QtCore.QSize(30, 30))
        self.btn_open_add.setObjectName("btn_open_add")
        self.horizontalLayout_2.addWidget(self.btn_open_add)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.widget_4 = QtWidgets.QWidget(Board)
        self.widget_4.setObjectName("widget_4")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.widget_4)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.pte_task_detail = QtWidgets.QPlainTextEdit(self.widget_4)
        self.pte_task_detail.setObjectName("pte_task_detail")
        self.verticalLayout_9.addWidget(self.pte_task_detail)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.ckb_notify = QtWidgets.QCheckBox(self.widget_4)
        self.ckb_notify.setObjectName("ckb_notify")
        self.horizontalLayout_10.addWidget(self.ckb_notify)
        self.dte_notfify = QtWidgets.QDateTimeEdit(self.widget_4)
        self.dte_notfify.setObjectName("dte_notfify")
        self.horizontalLayout_10.addWidget(self.dte_notfify)
        self.verticalLayout_9.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.btn_add = QtWidgets.QPushButton(self.widget_4)
        self.btn_add.setObjectName("btn_add")
        self.horizontalLayout_11.addWidget(self.btn_add)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem1)
        self.btn_cancel = QtWidgets.QPushButton(self.widget_4)
        self.btn_cancel.setObjectName("btn_cancel")
        self.horizontalLayout_11.addWidget(self.btn_cancel)
        self.verticalLayout_9.addLayout(self.horizontalLayout_11)
        self.verticalLayout.addWidget(self.widget_4)
        self.scrollArea = QtWidgets.QScrollArea(Board)
        self.scrollArea.setMinimumSize(QtCore.QSize(250, 700))
        self.scrollArea.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 267, 698))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout_8.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout_8.setSpacing(1)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.layout_task_items = QtWidgets.QVBoxLayout()
        self.layout_task_items.setContentsMargins(0, -1, 0, -1)
        self.layout_task_items.setSpacing(2)
        self.layout_task_items.setObjectName("layout_task_items")
        self.verticalLayout_8.addLayout(self.layout_task_items)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem2)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayout.addWidget(self.scrollArea)

        self.retranslateUi(Board)
        QtCore.QMetaObject.connectSlotsByName(Board)

    def retranslateUi(self, Board):
        _translate = QtCore.QCoreApplication.translate
        Board.setWindowTitle(_translate("Board", "Form"))
        self.lab_task_count.setText(_translate("Board", "TextLabel"))
        self.lab_title.setText(_translate("Board", "TextLabel"))
        self.btn_open_add.setText(_translate("Board", "+"))
        self.ckb_notify.setText(_translate("Board", "CheckBox"))
        self.btn_add.setText(_translate("Board", "添加"))
        self.btn_cancel.setText(_translate("Board", "取消"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Board = QtWidgets.QWidget()
    ui = Ui_Board()
    ui.setupUi(Board)
    Board.show()
    sys.exit(app.exec_())
