# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'modify_task.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ModifyTask(object):
    def setupUi(self, ModifyTask):
        ModifyTask.setObjectName("ModifyTask")
        ModifyTask.resize(352, 249)
        self.horizontalLayout = QtWidgets.QHBoxLayout(ModifyTask)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget_4 = QtWidgets.QWidget(ModifyTask)
        self.widget_4.setObjectName("widget_4")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.widget_4)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.pte_task_detail = QtWidgets.QPlainTextEdit(self.widget_4)
        self.pte_task_detail.setObjectName("pte_task_detail")
        self.verticalLayout_9.addWidget(self.pte_task_detail)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.ckb_notify = QtWidgets.QCheckBox(self.widget_4)
        self.ckb_notify.setObjectName("ckb_notify")
        self.horizontalLayout_10.addWidget(self.ckb_notify)
        self.dte_notfify = QtWidgets.QDateTimeEdit(self.widget_4)
        self.dte_notfify.setObjectName("dte_notfify")
        self.horizontalLayout_10.addWidget(self.dte_notfify)
        self.verticalLayout_9.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.btn_modify = QtWidgets.QPushButton(self.widget_4)
        self.btn_modify.setObjectName("btn_modify")
        self.horizontalLayout_11.addWidget(self.btn_modify)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem)
        self.btn_cancel = QtWidgets.QPushButton(self.widget_4)
        self.btn_cancel.setObjectName("btn_cancel")
        self.horizontalLayout_11.addWidget(self.btn_cancel)
        self.verticalLayout_9.addLayout(self.horizontalLayout_11)
        self.horizontalLayout.addWidget(self.widget_4)

        self.retranslateUi(ModifyTask)
        QtCore.QMetaObject.connectSlotsByName(ModifyTask)

    def retranslateUi(self, ModifyTask):
        _translate = QtCore.QCoreApplication.translate
        ModifyTask.setWindowTitle(_translate("ModifyTask", "Dialog"))
        self.ckb_notify.setText(_translate("ModifyTask", "CheckBox"))
        self.btn_modify.setText(_translate("ModifyTask", "修改"))
        self.btn_cancel.setText(_translate("ModifyTask", "取消"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ModifyTask = QtWidgets.QDialog()
    ui = Ui_ModifyTask()
    ui.setupUi(ModifyTask)
    ModifyTask.show()
    sys.exit(app.exec_())
